env:
    # Config
    CONFIG: config.sh

    # Telegram
    #TG_CHAT_ID: -1001595569305
    #TG_TOKEN: ENCRYPTED[525a4d7e4426bdaad7b33b8a958d7baaba34378fa92a7e15408031fa8612387af7eb911ce3466cb4e57b8644e69ef7bf]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Kernel CI"
  timeout_in: 240m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      #image: apon77/aosp
      cpu: 8
      memory: 16G

  Build_script:
      - curl -sL https://raw.githubusercontent.com/snnbyyds/kernel-CI/main/scripts/build.sh | bash
